In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
SEED = 20201129
np.random.seed(SEED)
plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus']=False #用来正常显示负号

# 矩阵和向量积

In [2]:
x = np.array([1,2,3,4,5])
y = np.array([2,3,4,5,6])
z = np.dot(x,y)
print(z)
print(type(x))

70
<class 'numpy.ndarray'>


In [3]:
x = np.random.randint(3,10,size=(3,3))
y = np.random.randint(4,12,size=(3,3))
print(x)
print(y)

[[6 6 6]
 [8 3 9]
 [6 4 3]]
[[9 4 8]
 [5 8 6]
 [8 7 5]]


In [4]:
z = np.dot(x,y)
print(z)

[[132 114 114]
 [159 119 127]
 [ 98  77  87]]


In [5]:
print(np.dot(y,x))

[[134  98 114]
 [130  78 120]
 [134  89 126]]


# 矩阵特征值与特征向量

In [6]:
x = np.diag((1,2,3))
print(x)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
# 特征值
print(np.linalg.eigvals(x))

[1. 2. 3.]


In [8]:
# a为特征值，b为特征向量
a ,b = np.linalg.eig(x)
print(a)
print(b)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
for i in range(3):
    if np.allclose(a[i]*b[:,i],np.dot(x,b[:,i])):
        print("right")
    else:
        print("Error")

right
right
right


In [14]:
# 判断对称阵是否为正定阵
A = np.arange(16).reshape(4,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
A = A+A.T
print(A)

[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]


In [16]:
B = np.linalg.eigvals(A)
print(B)

[ 6.74165739e+01 -7.41657387e+00  1.82694656e-15 -1.72637110e-15]


In [17]:
if np.all(B>0):
    print("Yes")
else:
    print("No")

No


# 矩阵分解

In [18]:
A = np.array([[4,11,14],[8,7,-2]])
print(A)

[[ 4 11 14]
 [ 8  7 -2]]


In [21]:
u,s,vh = np.linalg.svd(A,full_matrices=False)
print(u.shape)
print(s.shape)
print(vh.shape)

(2, 2)
(2,)
(2, 3)


In [22]:
print(s)

[18.97366596  9.48683298]


In [23]:
print(np.diag(s))

[[18.97366596  0.        ]
 [ 0.          9.48683298]]


In [24]:
print(vh)

[[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]


In [28]:
np.dot(u,np.dot(np.diag(s),vh))

array([[ 4., 11., 14.],
       [ 8.,  7., -2.]])

# QR分解

In [30]:
A = np.array([[2,-2,3],[1,1,1],[1,3,-1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [31]:
q,r = np.linalg.qr(A)
print(q.shape)
print(q)

(3, 3)
[[-0.81649658  0.53452248  0.21821789]
 [-0.40824829 -0.26726124 -0.87287156]
 [-0.40824829 -0.80178373  0.43643578]]


In [33]:
print(r.shape)
print(r)

(3, 3)
[[-2.44948974  0.         -2.44948974]
 [ 0.         -3.74165739  2.13808994]
 [ 0.          0.         -0.65465367]]


In [34]:
print(np.dot(q,r))

[[ 2. -2.  3.]
 [ 1.  1.  1.]
 [ 1.  3. -1.]]


In [35]:
print(np.allclose(np.dot(q.T,q),np.eye(3)))

True


In [38]:
A = np.random.randint(5,30,size=(4,5))
print(A)

[[19 22  8 27 18]
 [25 22  9 19 12]
 [13 24 11 19  5]
 [ 6  6 14 14 17]]


In [39]:
q,r = np.linalg.qr(A,mode='complete')
print(q.shape)
print(q)

(4, 4)
[[-0.55055121  0.08965311  0.18034061  0.81014378]
 [-0.72440948 -0.50124919  0.10782027 -0.46081986]
 [-0.37669293  0.85881393 -0.01977827 -0.34662645]
 [-0.17385828 -0.05612674 -0.97747679  0.10565138]]


In [40]:
print(r.shape)
print(r)

(4, 5)
[[-34.51086785 -38.13291528 -17.50173315 -38.21984442 -23.44189093]
 [  0.          11.21966009   4.86716105   8.42858966  -1.0613192 ]
 [  0.           0.         -11.48912878  -7.14268073 -12.17602262]
 [  0.           0.           0.           8.01152178   9.11569111]]


In [41]:
print(np.dot(q,r))

[[19. 22.  8. 27. 18.]
 [25. 22.  9. 19. 12.]
 [13. 24. 11. 19.  5.]
 [ 6.  6. 14. 14. 17.]]


In [44]:
print(np.allclose(np.dot(q,q.T),np.eye(4)))

True


# Cholesky分解

In [45]:
A = np.array([[1,1,1,1],[1,3,3,3],[1,3,5,5],[1,3,5,7]])
print(A)

[[1 1 1 1]
 [1 3 3 3]
 [1 3 5 5]
 [1 3 5 7]]


In [46]:
print(np.linalg.eigvals(A))

[13.13707118  1.6199144   0.51978306  0.72323135]


In [48]:
L = np.linalg.cholesky(A)
print(L)

[[1.         0.         0.         0.        ]
 [1.         1.41421356 0.         0.        ]
 [1.         1.41421356 1.41421356 0.        ]
 [1.         1.41421356 1.41421356 1.41421356]]


In [49]:
print(np.dot(L,L.T))

[[1. 1. 1. 1.]
 [1. 3. 3. 3.]
 [1. 3. 5. 5.]
 [1. 3. 5. 7.]]


# 矩阵的范数
## 向量的范数

In [52]:
x = np.array([1,2,3,4])
print(np.linalg.norm(x,ord=1))

10.0


In [53]:
print(np.linalg.norm(x,ord=2))

5.477225575051661


In [55]:
print(np.sum(np.abs(x)**2)**0.5)

5.477225575051661


In [58]:
print(np.linalg.norm(x,ord=-np.inf))
print(np.min(np.abs(x)))

1.0
1


In [59]:
print(np.linalg.norm(x,ord=np.inf))
print(np.max(np.abs(x)))

4.0
4


## 矩阵的范数

In [61]:
A = np.array([[1,1,1,1],[1,3,3,3],[1,3,5,5],[1,3,5,7]])
print(A)

[[1 1 1 1]
 [1 3 3 3]
 [1 3 5 5]
 [1 3 5 7]]


In [63]:
print(np.linalg.norm(A,ord=1))
print(np.max(np.sum(A,axis=0)))

16.0
16


In [64]:
print(np.linalg.norm(A,ord=2))
print(np.max(np.linalg.svd(A,compute_uv=False)))

13.137071184544087
13.137071184544087


In [65]:
print(np.linalg.norm(A,ord=np.inf))
print(np.max(np.sum(A,axis=1)))

16.0
16


In [66]:
print(np.linalg.norm(A,ord='fro'))
print(np.sqrt(np.trace(np.dot(A.T,A))))

13.2664991614216
13.2664991614216


## 计算方阵的行列式

In [68]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [69]:
print(np.linalg.det(x))

-2.0000000000000004


## 计算矩阵的秩

In [71]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
r = np.linalg.matrix_rank(I)
print(r)

3


In [75]:
I[1][1] = 0
print(I)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


In [76]:
r = np.linalg.matrix_rank(I)
print(r)

2


## 计算矩阵的迹

In [78]:
x = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
print(x)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [79]:
y = np.array([[5,4,2],[1,7,9],[0,4,5]])
print(y)

[[5 4 2]
 [1 7 9]
 [0 4 5]]


In [82]:
print(np.trace(x))
print(np.trace(np.transpose(x)))

13
13


In [83]:
print(np.trace(y))

17


In [84]:
print(np.trace(x+y))

30


## 逆矩阵

In [90]:
A = np.array([[1,-2,1], [0, 2,-1], [1, 1,-2]])
print(A)

[[ 1 -2  1]
 [ 0  2 -1]
 [ 1  1 -2]]


In [91]:
A_det = np.linalg.det(A)
print(A_det)

-2.9999999999999996


In [92]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 3.33333333e-01  1.00000000e+00 -3.33333333e-01]
 [ 6.66666667e-01  1.00000000e+00 -6.66666667e-01]]


In [95]:
print(np.allclose(np.dot(A,A_inv),np.eye(3)))

True


In [96]:
print(np.allclose(np.dot(A_inv,A),np.eye(3)))

True


In [98]:
A_companion = A_inv*A_det
A_companion

array([[-3.00000000e+00, -3.00000000e+00,  3.33066907e-16],
       [-1.00000000e+00, -3.00000000e+00,  1.00000000e+00],
       [-2.00000000e+00, -3.00000000e+00,  2.00000000e+00]])

## 求解线性方程组

In [100]:
# x + 2y + z = 7
# 2x ‐ y + 3z = 7
# 3x + y + 2z =18

In [102]:
A = np.array([[1,2,1],[2,-1,3],[3,1,2]])
b = np.array([7,7,18])
x = np.linalg.solve(A,b)
print(x)

[ 7.  1. -2.]


In [103]:
print(x.shape)

(3,)


In [104]:
print(np.dot(A,x))

[ 7.  7. 18.]


In [105]:
print(np.dot(np.linalg.inv(A),b))

[ 7.  1. -2.]
