In [2]:
import numpy as np
SEED = 20201124

## 二进制文件

In [8]:
outpath = '19期Numpy入门下/test.npy'
x = np.random.uniform(0,1,[3,5])
print(x)
np.save(outpath,x)

[[0.55938981 0.62556505 0.682231   0.16525988 0.7981054 ]
 [0.89850709 0.32148282 0.36666286 0.02737746 0.15562727]
 [0.48018743 0.32452507 0.43399027 0.15538189 0.61253844]]


In [10]:
y = np.load(outpath)
print(y)

[[0.55938981 0.62556505 0.682231   0.16525988 0.7981054 ]
 [0.89850709 0.32148282 0.36666286 0.02737746 0.15562727]
 [0.48018743 0.32452507 0.43399027 0.15538189 0.61253844]]


In [11]:
1+1

2

In [14]:
outpath1 = "19期Numpy入门下/test.npz"
x = np.linspace(0,np.pi,5)
y = np.sin(x)
z = np.cos(x)
print(x)
print(y)
np.savez(outpath1,x,y,z_d=z)

[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


In [17]:
data = np.load(outpath1)
print(data.files)
print(data['arr_0'])
print(data['arr_1'])
print(data['z_d'])

['z_d', 'arr_0', 'arr_1']
[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]


## 文本文件

In [24]:
outpath2 = "19期Numpy入门下/test.txt"
x = np.arange(0,10).reshape(2,-1)
print(x)
np.savetxt(outpath2,x,fmt='%.3f', delimiter=' ')

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
y = np.loadtxt(outpath2,delimiter=' ')
print(y)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [26]:
outpath3 = "19期Numpy入门下/test.csv"
x = np.arange(0,10,0.5).reshape(4,-1)
print(x)
np.savetxt(outpath3,x,fmt='%.3f', delimiter=',')
y = np.loadtxt(outpath3,delimiter=',')
print(y)

[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]
[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]


In [27]:
outpath4 = "19期Numpy入门下/data.csv"
x = np.loadtxt(outpath4,delimiter=',',skiprows=1)
print(x)

[[  1.  123.    1.4  23. ]
 [  2.  110.    0.5  18. ]
 [  3.  164.    2.1  19. ]]


In [28]:
x = np.loadtxt(outpath4,delimiter=',',skiprows=1,usecols=(1,2))
print(x)

[[123.    1.4]
 [110.    0.5]
 [164.    2.1]]


In [31]:
# unpack：当加载多列数据时是否需要将数据列进行解耦赋值给不同的变量
val1,val2 = np.loadtxt(outpath4,delimiter=',',skiprows=1,usecols=(1,2),unpack=True)
print(val1)
print(val2)

[123. 110. 164.]
[1.4 0.5 2.1]


In [33]:
x = np.genfromtxt(outpath4,delimiter=',',names=True)
print(x)
print(type(x))
print(x.dtype)

[(1., 123., 1.4, 23.) (2., 110., 0.5, 18.) (3., 164., 2.1, 19.)]
<class 'numpy.ndarray'>
[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')]


In [34]:
print(x['id'])
print(x['value1'])
print(x['value2'])
print(x['value3'])

[1. 2. 3.]
[123. 110. 164.]
[1.4 0.5 2.1]
[23. 18. 19.]


## 文本格式选项

In [35]:
np.set_printoptions(precision=4)
x = np.array([1.123456789])
print(x)

[1.1235]


In [36]:
np.set_printoptions(threshold=20)
x = np.arange(50)
print(x)

[ 0  1  2 ... 47 48 49]


In [39]:
eps = np.finfo(float).eps
x = np.arange(4)
print(x)
x = x**2-(x+eps)**2
print(x)
# 当 suppress=True ，表示小数不需要以科学计数法的形式输出，默认是False
np.set_printoptions(suppress=True)
print(x)

[0 1 2 3]
[-4.9304e-32 -4.4409e-16  0.0000e+00  0.0000e+00]
[-0. -0.  0.  0.]


In [43]:
x = np.linspace(0,10,10)
np.set_printoptions(precision=2,suppress=True,threshold=5)
print(x)

[ 0.    1.11  2.22 ...  7.78  8.89 10.  ]


In [44]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 5,
 'floatmode': 'maxprec',
 'precision': 2,
 'suppress': True,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}